---
version: 2.1
orbs:
  release-management: salesforce/npm-release-management@dev:alpha

jobs:
  yarn:
    executor: release-management/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: clean
          command: yarn clean
      - run:
          name: compile
          command: yarn compile

workflows:
  version: 2
  test-and-release:
    jobs:
      - release-management/pin-dependencies:
            dryrun: true
#     need to commit changes here?
      - yarn
      - release-management/validate-pr:
          filters:
            branches:
              ignore: master
      - release-management/release-package:
          dryrun: true
          sign: true
          github-release: true
#          requires:
#            - node-latest
#          filters:
#            branches:
#              only: master
#
