---
version: 2.1
orbs:
  release-management: salesforce/npm-release-management@dev:alpha

jobs:
  yarn:
    executor: release-management/default
    steps:
      - checkout
      - run:
          name: Install dependencies + Compile + Clean
          command: |
            yarn;
            yarn compile;
            yarn clean;

  commit:
    executor: release-management/default
    steps:
      - checkout
      - run:
          name: commit package.json change
          command: |
            git status;
            # if we have ONLY changed the package.json then we can commit and push
            if  git status --porcelain v1 | grep 'package.json' && git status --porcelain v1 | wc -l == 1; then
              git commit -m "Automatically adding package.json [skip ci]";
              git push;
              exit 0;
            fi

            # we've changed other things, so error
            echo "ERROR: more files were changed than expected";
            exit 1


workflows:
  version: 2
  test-and-release:
    jobs:
      - release-management/pin-dependencies
      - commit
      - yarn
      - release-management/validate-pr:
          filters:
            branches:
              ignore: master
      - release-management/release-package:
          dryrun: true
          tag: testing
          sign: true
          github-release: true
          use-tests: false
