---
version: 2.1
orbs:
  release-management: salesforce/npm-release-management@4

workflows:
  version: 2.1
  test-and-release:
    jobs:
      - release-management/pin-dependencies
      - release-management/validate-pr:
          filters:
            branches:
              ignore: main
      - release-management/test-package:
          name: node-latest
          node_version: latest
      - release-management/test-package:
          name: node-12
      - release-management/release-package:
          tag: testing
          sign: true
          github-release: true
          requires:
            - release-management/pin-dependencies
            - node-latest
          filters:
            branches:
              only: main
