---
version: 2.1
orbs:
  release-management: salesforce/npm-release-management@dev:alpha

jobs:
  yarnSteps:
    - run:
        name: Install Dependencies
        command: yarn
    - run:
        name: Yarn clean
        command: yarn clean
    - run:
        name: Yarn compile
        command: yarn compile

workflows:
  version: 2
  test-and-release:
    jobs:
      - release-management/pin-dependencies:
            tag: 'latest'
            dryrun: true
#     need to commit changes here?
      - yarnSteps
      - release-management/validate-pr:
          filters:
            branches:
              ignore: master
      - release-management/release-package:
          dryun: true
          sign: true
          github-release: true
          requires:
            - node-latest
          filters:
            branches:
              only: master
