---
version: 2.1
orbs:
  release-management: salesforce/npm-release-management@dev:alpha

workflows:
  version: 2
  test-and-release:
    jobs:
      - release-management/pin-dependencies:
          tag: 'latest'
          dryrun: true
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: clean
          command: yarn clean
      - run:
          name: compile
          command: yarn compile

#          need to commit changes?

    - release-management/validate-pr:
        filters:
          branches:
            ignore: master
    - release-management/release-package:
        dryrun: true
        sign: true
        github-release: true
        requires:
          - node-latest
        filters:
          branches:
            only: master
