---
version: 2.1
orbs:
  release-management: salesforce/npm-release-management@dev:alpha
# change
workflows:
  version: 2.1
  test-and-release:
    jobs:
      - release-management/pin-dependencies
      - release-management/validate-pr:
          filters:
            branches:
              ignore: master
      - release-management/release-package:
          tag: testing
          sign: true
          github-release: true
          requires:
            - release-management/pin-dependencies
