---
version: 2.1
orbs:
  release-management: salesforce/npm-release-management@dev:alpha

workflows:
  version: 2.1
  test:
    jobs:
      - release-management/validate-pr:
          filters:
            branches:
              ignore: main
      - release-management/test-package:
          name: node-latest
          node_version: latest
      - release-management/test-package:
          name: node-12

  release:
    jobs:
      - release-management/test-package:
          name: node-latest
          node_version: latest
      - release-management/test-package:
          name: node-12
      - approval:
          type: approval
          requires:
            - node-latest
            - node-12
      - release-management/release-package:
          dry-run: true
          tag: testing
          sign: true
          pre-job-steps:
            - release-management/pin-dependencies
          github-release: true
          requires:
            - approval
