---
version: 2.1
orbs:
  release-management: salesforce/npm-release-management@dev:alpha

jobs:
  yarn:
    executor: release-management/default
    steps:
      - run:
          name: Install dependencies + Compile + Clean
          command: |
            yarn install --force;
            yarn compile;
            yarn clean;

  commit:
    executor: release-management/default
    steps:
      - run:
          name: commit package.json change
          command: |
            git status;
            # if we have ONLY changed the package.json then we can commit and push
            if  git status --porcelain v1 | grep 'package.json' && git status --porcelain v1 | wc -l == 1; then
              git commit -m "Automatically adding package.json [skip ci]";
              git push;
              exit 0;
            fi

            # there are no changes to be committed.
            if  git status --porcelain v1 | grep 'package.json' && git status --porcelain v1 | wc -l == 0; then
              echo "No Changes Detected... continuing";
              exit 0;
            fi

            # we've changed other things, so error
            if  git status --porcelain v1 | grep 'package.json' && git status --porcelain v1 | wc -l > 1; then
              echo "ERROR: more files were changed than expected";
              exit 1
            fi

  pinAndCommit:
    executor: release-management/default
    steps:
      - release-management/pin-dependencies
      - yarn:
          requires:
            - commit
      - commit:
          requires:
            - release-management/pin-dependencies

workflows:
  version: 2.1
  test-and-release:
    jobs:
      - checkout
      - pinAndCommit
      - release-management/validate-pr:
          filters:
            branches:
              ignore: master
      - release-management/release-package:
          tag: testing
          sign: true
          github-release: true
          use-tests: false
          requires:
            - yarn
