---
version: 2.1
orbs:
  release-management: salesforce/npm-release-management@4

workflows:
  version: 2.1
  test:
    jobs:
      - release-management/validate-pr:
          filters:
            branches:
              ignore: main
      - release-management/test-package:
          name: node-latest
          node_version: latest
      - release-management/test-package:
          name: node-12

  release:
    jobs:
      - release-management/test-package:
          name: node-latest
          node_version: latest
          filters:
            branches:
              only: main
      - release-management/test-package:
          name: node-12
          filters:
            branches:
              only: main
      - approval:
          type: approval
          requires:
            - node-latest
            - node-12
      - release-management/release-package:
          tag: latest-rc
          sign: true
          pre-job-steps:
            - release-management/pin-dependencies:
                tag: latest-rc
          github-release: true
          requires:
            - approval
